MAX_PLAYERS_SMALL_SERVER = 1.024e18
MAX_PLAYERS_MEDIUM_SERVER = 1.024e19
MAX_PLAYERS_LARGE_SERVER = 1.024e20

def max_players_on_server():
    global MAX_PLAYERS_SMALL_SERVER, MAX_PLAYERS_MEDIUM_SERVER, MAX_PLAYERS_LARGE_SERVER
    return MAX_PLAYERS_SMALL_SERVER, MAX_PLAYERS_MEDIUM_SERVER, MAX_PLAYERS_LARGE_SERVER 

